[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.dfx-build]
description = "Build canisters"
dependencies = []
script = "./scripts/dfx-build.sh"
workspace = false

[tasks.run]
description = "Run app"
dependencies = []
command = "cargo"
args = ["run"]
workspace = false

[tasks.test]
description = "Run unit tests"
command = "cargo"
args = ["test", "--lib"]
dependencies = ["did"]
workspace = false

[tasks.integration-tests]
description = "Run integration tests"
script = "./scripts/integration-tests.sh"
dependencies = ["did", "dfx-build"]
workspace = false

[tasks.deploy-local]
description = "Deploy testnet with dfx"
script = "./scripts/deploy_local.sh"
dependencies = ["dfx-setup", "dfx-build", "did"]
workspace = false

[tasks.lint]
description = "Run lint"
command = "cargo"
args = ["clippy", "--", "-Dwarnings"]
workspace = false

[tasks.format]
description = "Run the cargo rustfmt plugin."
command = "cargo"
args = ["fmt", "--all"]

[tasks.check-format]
description = "Run the cargo rustfmt plugin."
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.did]
description = "Generate did files"
dependencies = ["dip721-canister-did", "dfx-generate"]
workspace = false

[tasks.dip721-canister-did]
description = "Generate did files for dip721-canister"
script = "cargo run --bin dip721-canister-did  --features did > src/dip721-canister.did"
workspace = false

[tasks.dfx-generate]
description = "Generate dfx did"
command = "dfx"
args = ["generate"]
workspace = false

[tasks.dfx-setup]
description = "setup dfx"
script = "./scripts/dfx-setup.sh"
workspace = false
